name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
       client-id: ${{secrets.service_principal}}
       tenant-id: ${{secrets.tenant}}
       subscription-id: ${{secrets.subscription_id}}
    - name: Build and push image
      id: build-image
      run: |
       az acr build --image netcoresample:latest --registry ${{ secrets.registry }} --file "Dockerfile" .
    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        # Version of helm
        version: v3.12.0
    - name: Helm registry login
      id: helm-registry-login
      run: |
       export HELM_EXPERIMENTAL_OCI=1
       helm registry login ${{ secrets.registry }}.azurecr.io --username ${{secrets.service_principal}} --password ${{secrets.service_principal_password}}
    - name: Helm package
      id: helm-package
      run: |
       helm package charts
    - name: helm push
      id: helm-push
      run: |
       helm push net-core-sample-chart-0.1.0.tgz oci://${{ secrets.registry }}.azurecr.io/helm
      

      
